print("my First Program of python")
import cv2
personImage = cv2.imread("./Images/photo1.jpeg")
# cv2.imshow('Original Image', personImage)
gray_image = cv2.cvtColor(personImage, cv2.COLOR_BGR2GRAY)
cv2.imshow("gray_image", gray_image)
cv2.waitKey(0)
# cv2.imwrite('./Images/Output/photo1_gray.jpg', gray_image)
gaussian_image = cv2.GaussianBlur(personImage, (15, 15), 0)
cv2.imshow("gaussian_image", gaussian_image)
cv2.waitKey(0)
# cv2.imwrite('./Images/Output/photo1_gaussian.jpg', gaussian_image)
edges_image = cv2.Canny(personImage, 100, 200)
cv2.imshow("edges_image", edges_image)
cv2.waitKey(0)
# cv2.imwrite('./Images/Output/photo1_edges.jpg', edges_image)